version: '3'

services:
  frontend:
    build:
      context: ./ml-kurkkumopo-frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  backend:
    build:
      context: ./ml-kurkkumopo-backend/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - model:/src/model

  training:
    build:
      context: ./ml-kurkkumopo-training/
      dockerfile: Dockerfile
    volumes:
      - model:/src/model
      - imgs:/src/imgs
      - data:/src/data

volumes:
  model:
  imgs:
  data:
