version: '3'

services:
  frontend:
    image: 23_frontend
    ports:
      - 5000:5000

  backend:
    image: 23_backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=backend_db
      - POSTGRES_USER=devopswdocker
      - POSTGRES_PASSWORD=surströmming
      - POSTGRES_DATABASE=backend_db

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data

  backend_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=devopswdocker
      - POSTGRES_PASSWORD=surströmming
      - POSTGRES_DB=backend_db
    volumes:
      - ./database:/var/lib/postgresql/data

  #nginx:
  #  image: nginx:latest
  #  volumes:
  #    - $PWD/nginx.conf:/etc/nginx/nginx.conf
  #  ports:
  #    - 80:80

# Still using 2.3 images
